### ISSUE TITLE
Could you add some documentation how to use this?

### ISSUE THREAD

**Issue by jaresty** [C-Loftus/talon-ai-tools#10]
https://github.com/C-Loftus/talon-ai-tools/blob/62a1ad117ef5433462eb6dddb59bd6150683688f/GPT/gpt-shell.talon#L7

I tried to use the model shell functionality but couldn't figure out how to use it. Could you add something to the read me with some examples?

**Comment by C-Loftus** [comment]
` model shell list all the python files in the current directory`

returns `ls *.py`  from which I can then say `paste model output`
I can adds some additional documentation but does that make sense?  Is something not working?  just want to be on the same page

**Comment by jaresty** [comment]
I'm not sure why, but it does not seem to be picking up my words as words. When I tried using that example command, it recognized everything after shell as talon commands instead of dictation. I'm not sure why that is?

**Comment by C-Loftus** [comment]
Did you pull the repository? If you are saying the command all in one go and have the command defined properly, it should work fine. There is just a 'model shell' command that operates upon the selected text as well, but that shouldn't be triggered unless you pause or say something that wouldn't be matched as user.text.

**Comment by jaresty** [comment]
That was the problem. Sorry about that!
