### ISSUE TITLE
`edit.selected()` text can return the line of text under the cursor even if no text is selected

### ISSUE THREAD

**Issue by C-Loftus** [C-Loftus/talon-ai-tools#148]
- If nothing is explicitly selected, seems like Talon views selected text as everything under the cursor in the editor 
    -  i.e. it seems to select the entire line of code in vscode if no text is selected
- Not clear why this is the case. Will have to look into this.
- This might be related to why some users were getting weird behavior; not a huge deal though since the model is usually good at ignoring irrelevant info

**Comment by wolfmanstout** [comment]
This is specifically a vscode behavior, and it can be turned off with the following setting: `"editor.emptySelectionClipboard": false`

This causes problems with Talon community features too like context-sensitive dictation.

**Comment by C-Loftus** [comment]
Ah cool thank you for clarifying!
