### ISSUE TITLE
Reading Out Markdown

### ISSUE THREAD

**Issue by Mark-Phillipson** [C-Loftus/talon-ai-tools#160]
When the model is reading back the results to speech and it encounters the markdown characters for a heading or title (###), it explicitly says "hashtag hashtag hashtag." Can we address this by ignoring it or using another method?

Maybe get the model to return plaintext only?

**Comment by C-Loftus** [comment]
I am curious, what prompt/use case was generating markdown for you? Have you updated the repository recently? I thought our prompt is pretty strict at making sure there isn't markdown formatting unless it is requested. 

Assuming this is an issue though, there are some heuristics that can be done 

Let me know if you have any other opinions about the text to speech functionality

**Comment by Mark-Phillipson** [comment]
Okay my bad I had the system prompt setup in settings without the markdown removal request.

**Comment by Mark-Phillipson** [comment]
The best use case so far with some programming code selected:

Model Explain To Speech

I'm not sure if this is possible but can you cancel once the speaking starts?

**Comment by C-Loftus** [comment]
Sight free talon has a function called 

actions.user.cancel_current_speaker()

Assuming you have it installed you can call this or define a new talon command to call it to stop speech. 

Perhaps `model stop speech` would be a good command to add. If you try this and feel is works feel free to submit a PR, should be quite simple
