### ISSUE TITLE
Add autoformatter

### ISSUE THREAD

**Issue by pokey** [C-Loftus/talon-ai-tools#17]
we should be able to just steal the pre-commit setup from community

_Originally posted by @pokey in https://github.com/C-Loftus/talon-ai-tools/issues/13#issuecomment-1932274685_

**Comment by C-Loftus** [comment]
I tried to set that up, but could not built talonfmt locally on windows due to treesitter. Must be something on my end, but didn't have success

**Comment by pokey** [comment]
Interesting. In theory that shouldn't matter as it just needs to run in CI

Alternatively, we could start with just the Python stuff. That's the most important piece imo
