### ISSUE TITLE
Do we always want to set clipboard to result?

### ISSUE THREAD

**Issue by pokey** [C-Loftus/talon-ai-tools#7]
Seems a bit surprising

https://github.com/C-Loftus/talon-ai-tools/blob/de8e3fc34e971a4559a90b1ae0019403d707a17b/GPT/gpt.py#L99-L100

https://github.com/C-Loftus/talon-ai-tools/blob/de8e3fc34e971a4559a90b1ae0019403d707a17b/GPT/gpt.py#L106-L107

**Comment by C-Loftus** [comment]
I agree it might not be necessary. The reason I have this is that in the past there have been instances in which while I was working, the focus was shifted for the cursor and then it could not be pasted. So then I would have to redo the command.  Honestly this is probably not super necessary anyways for most people.

 If you think this is unnecessary then I will get rid of it

**Comment by jaresty** [comment]
I don't like things messing with my clipboard unless I ask them to, so my vote would be to only do so when the command specifies the result goes to the clipboard.

**Comment by C-Loftus** [comment]
Okay I have changed this and pushed.  if for some reason this becomes an issue for others in the future then perhaps we can have some sort of additional argument that defaults to true that can be contextually overwritten to have true in case they always want to have the clipboard.

 but for now I will not do that and keep it simple
