### ISSUE TITLE
'from clip' source for running prompt

### ISSUE THREAD

**Issue by jaresty** [C-Loftus/talon-ai-tools#73]
I would like to be able to run a prompt on the contents of my clipboard. I would also like to be able to put the result into my clipboard.

We discussed having the concept of 'prompt sources'. We already have prompt destinations. Valid examples of prompt destinations are these:

- clipped
- before
- after
- browser

I would like to have a way to specify a prompt sources similarly. A couple of examples are these:
- clipboard
- selection

There was some concern that it would be confusing to use the position alone to indicate source versus destination. For that reason, we were thinking that using 'from' to denote that this is a source would be helpful. Here are a couple examples:

- `model [from selection] apply clipped`
- `model from clip apply clipped`
- `model from clip summarize`

**Comment by pokey** [comment]
can you elaborate on that grammar?

**Comment by jaresty** [comment]
@C-Loftus can you help?  The idea was modeled on unix pipes (i.e. something on the left is a source and on the right is output) and we also wanted to prefix with 'from' so it's clearer (versus just saying 'model selection apply' or 'model clip apply'

**Comment by jaresty** [comment]
Valid options for 'from' that we had so far were 'selection' and 'clip'

**Comment by jaresty** [comment]
Part of the issue is our outputs currently have 'clip', 'selected', 'browser', 'above', and 'below' at the end, so we need a way to distinguish source and destination.

**Comment by pokey** [comment]
Shall we discuss in a meetup?

**Comment by pokey** [comment]
See also https://github.com/cursorless-dev/cursorless/issues/495

**Comment by jaresty** [comment]
I'd love to discuss but can't make the normal meetup times. I'll send a message on slack.

**Comment by jaresty** [comment]
This has been implemented now.
